package org.firstinspires.ftc.teamcode;

public enum AutonomousPlan {
    LEAVE_FROM_GOAL,
    LEAVE_FROM_AUDIENCE,
    SHOOT_THREE_FROM_AUDIENCE,
    SHOOT_THREE_FROM_GOAL,
    SHOOT_COLLECT_SHOOT_FROM_AUDIENCE,
    SHOOT_COLLECT_SHOOT_FROM_GOAL,
    DRIVE_SQUARE_TEST;
}
